---
- name: Automação de Serviços | Multilog S/A | Departamento de Infraestrutura |
  hosts: windows
  tasks:
    - name: Verificando status atual dos serviços.
      win_service_info:
        name: "{{ item }}"
      loop:
        - "wuauserv"
      register: services_status

    - name: Parando todos os Serviços que estão rodando neste momento.
      win_service:
        name: "{{ item.name }}"
        state: stopped
      loop: "{{ services_status.results | map(attribute='service') | selectattr('state', 'eq', 'running') | list }}"
      when: item.state == "running"

    - name: Iniciando todos os serviços parados para normalizar as aplicações da Multilog S/A
      win_service:
        name: "{{ item }}"
        state: started
      loop:
        - "wuauserv"