- name: Instalar Halcyon via Ansible
  hosts: target_linux
  become: yes
  tasks:
    - name: Baixar o arquivo Halcyon
      ansible.builtin.get_url:
        url: "https://github.com/mtlg-diogo/Ansible-MTLG/releases/download/halcyonar/halcyonar-linux-x86_64-v1.0.4017.0.tar.gz"
        dest: "/root/halcyonar-linux-x86_64-v1.0.4017.0.tar.gz"
        mode: '0644'

    - name: Extrair o arquivo tar
      ansible.builtin.shell:
        cmd: "tar xzvf /root/halcyonar-linux-x86_64-v1.0.4017.0.tar.gz"
        chdir: "/root"

    - name: Executar o script de instalação
      ansible.builtin.shell:
        cmd: "HALCYON_TOKEN='53H3TxddTBOal/6CBovJxAEA' bash install.sh"
        chdir: "/root"
