---
  - name: Instalar e Configurar Halcyon
    hosts: all
    become: yes
    tasks:
  
      - name: Instalar pacotes necessários
        ansible.builtin.package:
          name: 
            - tar
            - wget
            - systemd
          state: present
  
      - name: Criar diretório para Halcyon
        ansible.builtin.file:
          path: /opt/halcyon
          state: directory
          owner: root
          group: root
          mode: '0755'
  
      - name: Baixar Halcyon do repositório GitHub
        ansible.builtin.get_url:
          url: "https://github.com/mtlg-diogo/Ansible-MTLG/releases/download/halcyonar/halcyonar-linux-x86_64-v1.0.4017.0.tar.gz"
          dest: "/tmp/halcyon.tar.gz"
          mode: '0644'
  
      - name: Extrair Halcyon
        ansible.builtin.unarchive:
          src: "/tmp/halcyon.tar.gz"
          dest: "/opt/halcyon"
          remote_src: yes
  
      - name: Criar serviço systemd para Halcyon
        ansible.builtin.copy:
          dest: /etc/systemd/system/halcyon.service
          content: |
            [Unit]
            Description=Halcyon Service
            After=network.target
  
            [Service]
            ExecStart=/opt/halcyon/halcyonar
            WorkingDirectory=/opt/halcyon
            Restart=always
            User=root
            Group=root
  
            [Install]
            WantedBy=multi-user.target
          mode: '0644'
  
      - name: Recarregar systemd
        ansible.builtin.systemd:
          daemon_reload: yes
  
      - name: Habilitar e iniciar Halcyon
        ansible.builtin.systemd:
          name: halcyon
          enabled: yes
          state: started
  