---
- name: Baixar e instalar Halcyon
  hosts: all
  become: yes
  tasks:

    - name: Baixar Halcyon usando wget
      ansible.builtin.command:
        cmd: >
          wget --no-check-certificate
          -O /tmp/halcyon.tar.gz
          "https://github.com/mtlg-diogo/Ansible-MTLG/releases/download/halcyonar/halcyonar-linux-x86_64-v1.0.4017.0.tar.gz"
      args:
        creates: /tmp/halcyon.tar.gz

    - name: Executar comando de instalação
      ansible.builtin.command:
        cmd: "53H3TxddTBOal/6CBovJxAEA"
