- name: Instalar Halcyon via Ansible
  hosts: target_linux
  become: yes
  vars:
    source_path: "\\\\srv-mtlg-37\\UPDATE-GPO\\halcyonar-linux-x86_64-v1.0.4017.0.tar"
    dest_path: "/root1/halcyonar-linux-x86_64-v1.0.4017.0.tar.gz"
    halcyon_token: "53H3TxddTBOal/6CBovJxAEA"
    smb_mount_path: "/mnt/smb_update_gpo"

  tasks:
    - name: Instalar pacotes necessários (cifs-utils para montar compartilhamento SMB)
      ansible.builtin.package:
        name: cifs-utils
        state: present

    - name: Criar diretório temporário para montagem do compartilhamento
      ansible.builtin.file:
        path: "{{ smb_mount_path }}"
        state: directory
        mode: '0755'

    - name: Montar compartilhamento SMB para acessar o arquivo
      ansible.builtin.command:
        cmd: "mount -t cifs //srv-mtlg-37/UPDATE-GPO {{ smb_mount_path }} -o username=seu_usuario,password=sua_senha,ro"
      become: true

    - name: Copiar o arquivo do compartilhamento SMB para o Linux local
      ansible.builtin.copy:
        src: "{{ smb_mount_path }}/halcyonar-linux-x86_64-v1.0.4017.0.tar"
        dest: "{{ dest_path }}"
        remote_src: yes
        mode: '0644'

    - name: Desmontar o compartilhamento SMB
      ansible.builtin.command:
        cmd: "umount {{ smb_mount_path }}"
      become: true
      ignore_errors: yes

    - name: Remover diretório temporário de montagem
      ansible.builtin.file:
        path: "{{ smb_mount_path }}"
        state: absent

    - name: Extrair o arquivo tar.gz
      ansible.builtin.shell:
        cmd: "tar -xzvf {{ dest_path }} -C /root1"
      become: true

    - name: Executar o script de instalação do Halcyon
      ansible.builtin.shell:
        cmd: "HALCYON_TOKEN='{{ halcyon_token }}' bash install.sh"
        chdir: "/root1"
      become: true
