---
- name: Baixar e instalar Halcyon
  hosts: all
  become: yes
  tasks:

    - name: Baixar Halcyon usando wget
      ansible.builtin.command:
        cmd: >
          wget --no-check-certificate
          -O /tmp/halcyon.tar.gz
          "https://github.com/mtlg-diogo/Ansible-MTLG/releases/download/halcyonar/halcyonar-linux-x86_64-v1.0.4017.0.tar.gz"
      args:
        creates: /tmp/halcyon.tar.gz

    - name: Extrair Halcyon
      ansible.builtin.command:
        cmd: "tar xzvf /tmp/halcyon.tar.gz"
        chdir: "/tmp"

    - name: Executar script de instalação com token
      ansible.builtin.shell:
        cmd: "HALCYON_TOKEN='53H3TxddTBOal/6CBovJxAEA' bash install.sh"
        chdir: "/tmp"
