- name: Atualizar e reiniciar o Windows
  hosts: windows
  tasks:
    - name: Instalar atualizações no Windows e reiniciar se necessário
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
        reboot: yes
