- name: INICIANDO PROCESSO DE ATUALIZAÇÃO E REBOOT ( CASO NECESSÁRIO )
  hosts: windows
  tasks:
    - name: VERIFICANDO E INSTALANADO UPDATES
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
        reboot: yes
        reboot_timeout: 600  # Tempo em segundos para aguardar o reinício
