- name: INICIANDO PROCESSO DE ATUALIZAÇÃO DAS MÁQUINAS
  hosts: windows
  tasks:
    - name: BAIXANDO E INSTALANDO ATUALIZAÇÕES DE SEGURANÇA
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
        reboot: no  # Não reinicia a máquina automaticamente
