- name: INICIANDO PROCESSO DE ATUALIZAÇÃO DAS MAQUINAS
  hosts: windows
  tasks:
    - name: BAIXANDO E INSTALANDO ATUALIZAÇÃO QUE NÃO PRECISE REINICIAR A MAQUINA.
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
        reboot: no  # Não reinicia a máquina automaticamente
        exclude_reboot: yes  # Exclui atualizações que requerem reinício
